---
title: "p8105_hw2_yg2625"
author: "Yue Gu"
date: "October 2, 2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Library
```{r}
library(tidyverse)
library(readxl)
```

# Problem 1

Clean the data and convert the entry variable
```{r}
NYCsub_data = 
  read_csv("./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv") %>% 
  janitor::clean_names(dat = .) %>% 
  select(.data = ., line, station_name, station_latitude, station_longitude, route1:route11, entry, vending, entrance_type, ada, ada_notes) %>% 
  mutate(.data = ., entry = ifelse(entry == "YES", TRUE, FALSE))

NYCsub_data 
```


Answering question with data
```{r}
dim(NYCsub_data)
count(distinct(NYCsub_data, station_name))
count(subset(NYCsub_data, ada == TRUE))
count(subset(NYCsub_data, vending == "NO" & entry == TRUE))/count(NYCsub_data)
```

Reformat data and answer related question
```{r}
NYCsub_tidy_data = gather(NYCsub_data, key = route, value = route_name, route1:route11)

count(distinct(NYCsub_tidy_data, route_name == "A"))
count(subset(NYCsub_tidy_data, route_name == "A" & ada == TRUE))
```

# Problem 2

Read and clean the data from Mr. Trash
```{r}
Healthy_data = 
  read_excel("data/HealthyHarborWaterWheelTotals2017-9-26.xlsx", sheet = "Mr. Trash Wheel", range = cell_cols("A:N")) %>%
  janitor::clean_names(dat = .) %>% 
  filter(.data = ., dumpster != "") %>% 
  mutate(.data = ., sports_balls = as.integer(round(sports_balls)))
```

Read and clean precipitation data
```{r}
Prec_2016 =
  read_excel("data/HealthyHarborWaterWheelTotals2017-9-26.xlsx", sheet = "2016 Precipitation", range = cell_rows(2:15)) %>% 
  janitor::clean_names(dat = .) %>% 
  filter(.data = ., total != "") %>% 
  mutate(.data = ., year = "2016")

Prec_2017 =
  read_excel("data/HealthyHarborWaterWheelTotals2017-9-26.xlsx", sheet = "2017 Precipitation", range = cell_rows(2:15)) %>% 
  janitor::clean_names(dat = .) %>% 
  filter(.data = ., total != "") %>% 
  mutate(.data = ., year = "2017")

Prec_data = 
  left_join(Prec_2016, Prec_2017, by = "month") %>%
  filter(.data = ., month != "") %>% 
  mutate(.data = ., month = month.name)

```

Comment with incline code
```{r}
count(Healthy_data)
count(Prec_2016)
count(Prec_2017)
count(Prec_data)
median(Healthy_data$sports_balls)
max(Prec_2017$total)
```

## Problem 3


```{r}
library(p8105.datasets)
data(brfss_smart2010)
brfss_smart2010_tidy = 
  brfss_smart2010 %>% 
  janitor::clean_names() %>% 
  filter(.data = ., topic == "Overall Health") %>% 
  select(.data = ., -class, -topic, -question, -sample_size, -confidence_limit_low: -geo_location) %>% 
  spread(key = response, value = data_value) %>% 
  janitor::clean_names() %>% 
  mutate(.data = ., excellent_or_very_good = excellent + very_good)
  
```
